-- MySQL Script generated by MySQL Workbench
-- 10/21/14 10:34:41
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema modulo_upload
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modulo_upload` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `modulo_upload` ;

-- -----------------------------------------------------
-- Table `modulo_upload`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modulo_upload`.`admin` (
  `adm_id` INT NOT NULL AUTO_INCREMENT,
  `adm_usuario` VARCHAR(45) NULL,
  `adm_contrasena` VARCHAR(45) NULL,
  PRIMARY KEY (`adm_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modulo_upload`.`slide`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modulo_upload`.`slide` (
  `sli_id` INT NOT NULL AUTO_INCREMENT,
  `sli_img_nombre` VARCHAR(45) NULL,
  `sli_estado` ENUM('0','1','2') NULL DEFAULT '0',
  `sli_url` TEXT NOT NULL,
  `sli_fecha_creacion` DATETIME NULL,
  `admin_adm_id` INT NOT NULL,
  PRIMARY KEY (`sli_id`),
  UNIQUE INDEX `sli_nombre_UNIQUE` (`sli_img_nombre` ASC),
  INDEX `fk_slide_admin_idx` (`admin_adm_id` ASC),
  CONSTRAINT `fk_slide_admin`
    FOREIGN KEY (`admin_adm_id`)
    REFERENCES `modulo_upload`.`admin` (`adm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modulo_upload`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modulo_upload`.`noticia` (
  `not_id` INT NOT NULL AUTO_INCREMENT,
  `not_archivo_nombre` VARCHAR(45) NULL,
  `not_tipo` ENUM('pdf','url') NOT NULL,
  `not_url` TEXT NULL,
  `not_titulo` VARCHAR(45) NOT NULL,
  `not_fecha_creacion` DATETIME NULL,
  `not_estado` ENUM('0','1','2') NOT NULL DEFAULT '0',
  `not_img_nombre_vp` VARCHAR(45) NULL,
  `admin_adm_id` INT NOT NULL,
  PRIMARY KEY (`not_id`),
  UNIQUE INDEX `not_archivo_nombre_UNIQUE` (`not_archivo_nombre` ASC),
  INDEX `fk_noticia_admin1_idx` (`admin_adm_id` ASC),
  CONSTRAINT `fk_noticia_admin1`
    FOREIGN KEY (`admin_adm_id`)
    REFERENCES `modulo_upload`.`admin` (`adm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modulo_upload`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modulo_upload`.`log` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `log_descripcion` VARCHAR(45) NOT NULL DEFAULT 'Error inesperado.',
  `log_fecha_creacion` DATETIME NULL,
  `admin_adm_id` INT NOT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_log_admin1_idx` (`admin_adm_id` ASC),
  CONSTRAINT `fk_log_admin1`
    FOREIGN KEY (`admin_adm_id`)
    REFERENCES `modulo_upload`.`admin` (`adm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
